#! /bin/bash

_d4t()
{
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --bash-completion )
  COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )

  return 0
}

complete -F _d4t d4t
